# Generated by Django 2.2.1 on 2019-05-23 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inn', models.PositiveIntegerField(verbose_name='На складе')),
                ('name', models.CharField(max_length=200, verbose_name='Название контрагента')),
                ('web_site', models.CharField(max_length=200, verbose_name='Сайт')),
                ('is_website', models.BooleanField(default=False, verbose_name='Работоспособность вебсайта')),
                ('risk', models.CharField(blank=True, choices=[('STOP', 'стоп'), ('DOP_FOCUS', 'Доп. фокус'), ('OK', 'Ок')], max_length=15, null=True, verbose_name='Риск')),
                ('с_time', models.DateTimeField(blank=True, null=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
                'ordering': ['name'],
            },
        ),
    ]
