# Generated by Django 2.2.1 on 2019-05-27 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('counterparties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, verbose_name='email для уведомленияы')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='SourceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, verbose_name='url источника')),
            ],
            options={
                'verbose_name': 'Настройка источников',
                'verbose_name_plural': 'Настройки источников',
                'ordering': ['url'],
            },
        ),
        migrations.CreateModel(
            name='SparkSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cron_key', models.CharField(max_length=200, verbose_name='Периодичность обновления')),
            ],
            options={
                'verbose_name': 'Настройка СПАРК',
                'verbose_name_plural': 'Настройки СПАРК',
                'ordering': ['cron_key'],
            },
        ),
        migrations.AddField(
            model_name='counterparties',
            name='bankruptcy_procedure',
            field=models.CharField(blank=True, choices=[('STOP', 'Поданы иски, введена процедура банкротства'), ('DOP_FOCUS', 'Имеется сообщение кредитора о намерении подать заявление  о несостоятельности'), ('OK', 'Отсутствует')], max_length=15, null=True, verbose_name='Наличие процедуры банкротства'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_constituent_documents',
            field=models.CharField(blank=True, choices=[('STOP', 'Р 13001, новая редакция устава (полномочия, вынезение)'), ('DOP_FOCUS', 'Р 13001,  не влияющие на полномочия приятия решений руковдителем и составом участников'), ('OK', 'нет')], max_length=15, null=True, verbose_name='Изменение в учредительных документах'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_debt_load',
            field=models.CharField(blank=True, choices=[('STOP', 'Резкое увеличение долговой нагрузки: кредиты и займы (более 30%)'), ('DOP_FOCUS', 'Увеличение долговой нагрузки: кредиты и займы (до  30%)'), ('OK', 'Без существенных измнений')], max_length=15, null=True, verbose_name='Изменение долговой нагрузки: займы и кредиты'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_director',
            field=models.CharField(blank=True, choices=[('STOP', 'Возникновение массового директора'), ('DOP_FOCUS', 'Планируется'), ('OK', 'Нет и не планируется')], max_length=15, null=True, verbose_name='Смена директора'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_fixed_assets',
            field=models.CharField(blank=True, choices=[('STOP', 'Резкое снижение основных фондов (производственных, складских)'), ('DOP_FOCUS', 'Выбытие ОС и замена на арендованные площади'), ('OK', 'Расширение')], max_length=15, null=True, verbose_name='Изменение масштабов бизнеса'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_participants',
            field=models.CharField(blank=True, choices=[('STOP', 'Смена'), ('DOP_FOCUS', 'Планируется'), ('OK', 'Нет и не планируется')], max_length=15, null=True, verbose_name='Смена учредителей / участников'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_registration_address',
            field=models.CharField(blank=True, choices=[('STOP', 'Смена адреса на  массовый, уход в другой регион'), ('DOP_FOCUS', 'Планируется'), ('OK', 'Нет и не планируется')], max_length=15, null=True, verbose_name='Смена адреса регистрации'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='change_share_capital',
            field=models.CharField(blank=True, choices=[('STOP', 'Уменьшение'), ('DOP_FOCUS', 'Перераспределение долей'), ('OK', 'Отсутствует либо увеличение')], max_length=15, null=True, verbose_name='Изменение уставного капитала'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='changes_company_management',
            field=models.CharField(blank=True, choices=[('STOP', 'Смена  команды'), ('DOP_FOCUS', '-----'), ('OK', 'Без существенных измнений')], max_length=15, null=True, verbose_name='Изменения в менедженте компаниии'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='changing_scope_activities',
            field=models.CharField(blank=True, choices=[('STOP', 'Планируется резкая смена деятельности '), ('DOP_FOCUS', 'Информация о развитии иных непрофильных проектов, направлений'), ('OK', 'Нет изменений')], max_length=15, null=True, verbose_name='Изменение сферы деятельности'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='contact_phone_numbers',
            field=models.CharField(blank=True, choices=[('STOP', 'Недоступные контактные телефоны'), ('DOP_FOCUS', 'Невнятные и неконструктивных комментарии при взаимодействии, необснованные обещания'), ('OK', 'Доступны')], max_length=15, null=True, verbose_name='Контактные телефоны'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='credit_history',
            field=models.CharField(blank=True, choices=[('STOP', 'Частые случаи просрочек, иски  на курпные суммы, иски от банка'), ('DOP_FOCUS', 'Небольшие просрочки'), ('OK', 'Хорошая кредитная история')], max_length=15, null=True, verbose_name='Кредитная история  у контрагентов, поставщиков, заказчиков, в банках'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='executive_documents',
            field=models.CharField(blank=True, choices=[('STOP', 'Большое количество исполнительныз производство либо крупные исполнительные производства (более 30% от активов)'), ('DOP_FOCUS', 'Много, более 5% активов'), ('OK', 'Нет, только по ТК')], max_length=15, null=True, verbose_name='Наличие исполнительных документов'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='interaction_Customers',
            field=models.CharField(blank=True, choices=[('STOP', 'Приоставновка финансирования проекта/заказа, существенное смещение сроков оплаты за выполненные работы, иски.'), ('DOP_FOCUS', 'Изменение схемы финансирования проектов, сроков выполнения. Расторжение ранее заключенных контрактов. '), ('OK', 'Нет негативной информации по работе с Заказчиками')], max_length=15, null=True, verbose_name='Взаимодействие с Заказчиками'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='presence_litigation',
            field=models.CharField(blank=True, choices=[('STOP', 'Множество судебных споров в качестве ответчика либо на крупные суммы, либо с металлотрейдерами (более 30% от активов)'), ('DOP_FOCUS', 'Множество судебных споров либо несколько на крупные суммы в качестве истца, ответчика'), ('OK', 'Нет, только по ТК')], max_length=15, null=True, verbose_name='Наличие судебных споров'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='reorganization_procedure',
            field=models.CharField(blank=True, choices=[('STOP', 'Вывод активов, ликвидация'), ('DOP_FOCUS', 'Дружественная (в форме присоединения компаний группы, укрупнение)'), ('OK', 'Отсутствует либо в форме изменения ОПФ (ОАО -АО)')], max_length=15, null=True, verbose_name='Наличие процедуры реорганизации'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='resizing_business',
            field=models.CharField(blank=True, choices=[('STOP', 'Существенное сокращение выручки (более 30%), аномальный рост выручки (более 50%)'), ('DOP_FOCUS', 'Значительное  сокращение выручки (до 30%)'), ('OK', 'Рост, развитие')], max_length=15, null=True, verbose_name='Изменение уставного  капитала'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='transfer_of_business',
            field=models.CharField(blank=True, choices=[('STOP', 'Выведение внеоборотных активов (перевод на другое юр.лицо)'), ('DOP_FOCUS', 'Перераспределение заказов на другое юр.лицо, смещение закупки на другое юр.лицо '), ('OK', 'Нет изменений')], max_length=15, null=True, verbose_name='Перевод бизнеса на другое юр.лицо'),
        ),
        migrations.AddField(
            model_name='counterparties',
            name='unresolved_claims',
            field=models.CharField(blank=True, choices=[('STOP', 'Иски от ИФНС, арест счетов, приостановление деятельности,  претензии на крупные суммы  ( > 30 % активов). Проверка по причине хищения гос.средств'), ('DOP_FOCUS', 'Просрочка налоговых платежей, есть предписания надзорных органов'), ('OK', 'Нет')], max_length=15, null=True, verbose_name='Неурегулированных претензий со стороны /к гос.органам'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='inn',
            field=models.PositiveIntegerField(verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='counterparties',
            name='web_site',
            field=models.CharField(blank=True, max_length=200, verbose_name='Сайт'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('news', models.TextField(verbose_name='Новости')),
                ('customer_industry', models.CharField(blank=True, choices=[('STOP', 'Кризис в отрасли. Несоответствие компании "новым стандартам". '), ('DOP_FOCUS', 'Изменения законодательства.  Введение мер регулирования государством.'), ('OK', 'Стабильна, рост')], max_length=15, null=True, verbose_name='По отрасли клиента')),
                ('management_company', models.CharField(blank=True, choices=[('STOP', 'Негативные отклики, проблемы у команды, менеджмента компании,  учредителей, негативные отклики на форумах работодателя («черный список работодателей»).  Смена собственника, директора, негативные отзывы о работодателе . Смерть учредителя.   '), ('DOP_FOCUS', 'Губернаторский риск: компания под управлением приближенных к губернатору. Ключевые изменения в стратегии управления  компанией, проектами. '), ('OK', 'Хорошая репутация. Стабильные связи по проектам или   имеются связи с "приближенными к власти"')], max_length=15, null=True, verbose_name='По менеджменту компании')),
                ('company_business', models.CharField(blank=True, choices=[('STOP', 'Проблемы с проектами. Проблемы с крупным монопроектом.  Иск/иски   от банков.  Реестр недобросоветных поставщиков. Объявления о продаже производственных площадей на авито, др.специализированных сайтах'), ('DOP_FOCUS', 'Противоречивый новостной фон (проблемы у группы , у  одной из компаний группы, аффлированного банка)'), ('OK', 'Хороший новостной фон по проектам. Новые инвестиционные проекты. Улучшения. Досрочные исполнения.')], max_length=15, null=True, verbose_name='По компании как бизнесу')),
                ('objects_projects', models.CharField(blank=True, choices=[('STOP', 'Отрицательный новостной  фон, проблемы с проектами/объектами (проблемы с разрешениями на строительство, заморозка проекта, прекращение финансирования проекта), аварии'), ('DOP_FOCUS', 'Противоречивый новостной фон по объектам, проектам (проблемы с документацией,  изменение стоимости проекта, изменение схемы  финансирования проекта). Монопроект/монообъект'), ('OK', 'Рост портфеля заказов,  проектов. Крупные проекты, анансированные в СМИ')], max_length=15, null=True, verbose_name='По  объектам, проектам')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='counterparties.Counterparties')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['news'],
            },
        ),
    ]
